[package]
name = "molecule"
version = "0.0.5"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2018"
description = "Rust bindings for molecule."
homepage = "https://github.com/yangby-cryptape/molecule"
repository = "https://github.com/yangby-cryptape/molecule"
keywords = ["serialization"]
categories = ["encoding", "data-structures"]
license = "MIT"

[dependencies]
bytes = "~0.4"
faster-hex = "~0.3"

[badges]
maintenance = { status = "experimental" }
