[package]
name = "molecule"
version = "0.5.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "Rust bindings for molecule."
homepage = "https://github.com/nervosnetwork/molecule"
repository = "https://github.com/nervosnetwork/molecule"
keywords = ["serialization"]
categories = ["encoding", "data-structures"]
license = "MIT"

[dependencies]
cfg-if = "~0.1"
bytes = { version = "~0.5", optional = true }
faster-hex = { version = "~0.4", optional = true }

[features]
default = ["std"]
std = ["bytes", "faster-hex"]

[badges]
maintenance = { status = "experimental" }
