[package]
name = "molecule"
version = "0.4.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "Rust bindings for molecule."
homepage = "https://github.com/nervosnetwork/molecule"
repository = "https://github.com/nervosnetwork/molecule"
keywords = ["serialization"]
categories = ["encoding", "data-structures"]
license = "MIT"

[dependencies]
bytes = "~0.4"
faster-hex = "~0.4"

[badges]
maintenance = { status = "experimental" }
