[package]
name = "molecule-codegen"
version = "0.2.3"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "Code generator for molecule."
homepage = "https://github.com/yangby-cryptape/molecule"
repository = "https://github.com/yangby-cryptape/molecule"
keywords = ["molecule", "code-generation", "serialization"]
categories = [
    "parser-implementations",
    "development-tools::build-utils",
    "encoding",
    "data-structures"
]
license = "MIT"

[dependencies]
pest = "~2.1"
pest_derive = "~2.1"
quote = "~0.6"
proc-macro2 = "~0.4"
case = "~1.0"

[badges]
maintenance = { status = "experimental" }
